orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: ndukwearm19docker/docker-node-app
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

jobs:
    
  buildContainer4Server:

    executor: docker-publisher

    working_directory: ~/server

    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Archieve Docker Image
          command: docker save -o  image.tar $IMAGE_NAME
      - persist-to-workspace:
          root: .
          paths: 
            - ./image.tar


  publishLatestToHub: 
      executor: docker-publisher
      steps: 
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archieved Docker image
            command: docker load -i /tmp/workspace/image.tar
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - buildContainer4Server:
          filters:
            branches: 
              only: main
      - publishLatestToHub: 
          requires:
            - buildContainer4Server
                
                 
             
    
       
      


    
           
   
    

    
